events {}

http {
    server {
        listen 80;
        server_name makroteknik.co.uk www.makroteknik.co.uk;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Optional catch-all
        location / {
            return 301 https://$host$request_uri;
        }
    }
}
